#!/bin/bash

INFILE="$1"


if [ ! -e "$INFILE" ]; then
    echo "File $INFILE does not exist!"
    exit 1
fi

OUTFILE= basename "$INFILE"

./compiler < "$INFILE" > "$OUTFILE.s"

if [ $? != 0 ]; then
    echo "Compiler error: " "$?"
    exit 1
fi

nasm -f elf "$OUTFILE.s"

if [ $? != 0 ]; then
    echo "Assembler error: " "$?"
    exit 1
fi


gcc -c clink.c
ld -o "$OUTFILE" "$OUTFILE.o" clink.o -lc --dynamic-linker=/lib/ld-linux.so.2 -melf_i386


if [ $? != 0 ]; then
    echo "Linker error: " "$?"
    exit 1
fi


echo "Success!"
